param(
    [string]$SdkRoot = "C:\ffx-x3\FidelityFX-SDK",
    [string]$OpenShadersRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..\..\")).Path
)
$ErrorActionPreference = "Stop"
$Commit = "60f4ea81909200d8542eca14dccb2628b763a9a3"

function Require($cmd) {
    if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) { throw "Required command not found: $cmd" }
}
Require git
Require python

$parent = Split-Path $SdkRoot -Parent
New-Item -ItemType Directory -Force -Path $parent | Out-Null
if (-not (Test-Path (Join-Path $SdkRoot ".git"))) {
    git clone https://github.com/GPUOpen-LibrariesAndSDKs/FidelityFX-SDK.git $SdkRoot
}
Push-Location $SdkRoot
try {
    git fetch origin $Commit
    git checkout --detach $Commit
    if ((git rev-parse HEAD).Trim() -ne $Commit) { throw "FidelityFX checkout is not pinned commit $Commit" }

    $tool = Join-Path $OpenShadersRoot "tools\ffx-fg-x3"
    python (Join-Path $tool "audit_core_x3.py") $SdkRoot
    python (Join-Path $tool "apply_provider_x3.py") $SdkRoot
    python (Join-Path $tool "apply_core_x3.py") $SdkRoot

    $dx12 = Join-Path $SdkRoot "Kits\FidelityFX\framegeneration\fsr3\dx12"
    $sc = Join-Path $SdkRoot "Kits\FidelityFX\tools\ffx_sc\bin\FidelityFX_SC.exe"
    if (-not (Test-Path $sc)) { throw "FidelityFX_SC.exe missing: $sc" }

    # Only these two shader entry points consume changed GPU logic. The CB layout
    # remains the same size, so unchanged passes do not need regenerated bytecode.
    & (Join-Path $dx12 "BuildFrameInterpolationShaders.bat") "$dx12\" ".\" "ffx_frameinterpolation_setup_pass"
    if ($LASTEXITCODE -ne 0) { throw "setup shader generation failed: $LASTEXITCODE" }
    & (Join-Path $dx12 "BuildFrameInterpolationShaders.bat") "$dx12\" ".\" "ffx_frameinterpolation_pass"
    if ($LASTEXITCODE -ne 0) { throw "interpolation shader generation failed: $LASTEXITCODE" }

    $generated = Join-Path $dx12 "ffx_sc_output"
    $required = @(
      "ffx_frameinterpolation_setup_pass_permutations.h",
      "ffx_frameinterpolation_setup_pass_wave64_permutations.h",
      "ffx_frameinterpolation_setup_pass_16bit_permutations.h",
      "ffx_frameinterpolation_setup_pass_wave64_16bit_permutations.h",
      "ffx_frameinterpolation_pass_permutations.h",
      "ffx_frameinterpolation_pass_wave64_permutations.h",
      "ffx_frameinterpolation_pass_16bit_permutations.h",
      "ffx_frameinterpolation_pass_wave64_16bit_permutations.h"
    )
    foreach ($name in $required) {
        if (-not (Test-Path (Join-Path $generated $name))) { throw "Expected generated shader header missing: $name" }
    }
    Write-Host "X3 FidelityFX source + shader preparation complete." -ForegroundColor Green
    Write-Host "SDK: $SdkRoot"
    Write-Host "Generated headers: $generated"
} finally { Pop-Location }
